* Important
* Final Project;
data IBM;
infile '\\tsclient\Desktop\ST 635\Project\IBMM.csv' dlm=',' firstobs = 2;
input Age Attrition Travel DailyR Dep Dist Edu Edufield EmpCount Empno EnvirSatisf Gender HourlyR Jobinvol joblevel jobrole jobsatis martial monIncome MonthlyR ComNo Over18 Overtime SalaryHike Rating Relasatisf Standhours stock workingyear Training Balance YearsatCom YearRole LastPromYear YearMGR ;
run;
proc print data=IBM;
run;
*Cluster analysis;
proc standard data=IBM mean=0 std=1 out=IBMS;
var Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis;
run;
proc means data=IBMS;
run;
proc print data=IBMS;
run;
*Single method;
proc cluster data=IBMS simple noeigen method=single rsquare nonorm out=tree;
title 'Cluster Analysis Single';
var Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;
proc tree data=tree out=IBMsin nclusters=100;
copy Age Dist MonthlyR ComNo workingyear YearsatCom YearRole;
run;

*Centroid method;
proc cluster data=IBMS simple noeigen method = centroid rsquare nonorm out=tree;
title 'Cluster Analysis Centroid';
var Age Dist MonthlyR ComNo workingyear YearsatCom YearRole;
run;
proc tree data=tree out=IBMcen nclusters=100;
copy Age Dist MonthlyR ComNo workingyear YearsatCom YearRole;
run;

*Average method;
proc cluster data=IBMS simple noeigen method = average rsquare nonorm out=tree;
title 'Cluster Analysis Average';
var Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;
proc tree data=tree out=IBMavg nclusters=100;
copy Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;
*try average method with n=6;
proc tree data=tree out=IBMavg6 nclusters=6;
copy Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;
proc print data=IBMavg6;
run;
proc means data=IBMavg6;	
var Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;	
by cluster;
run;
proc sort data=IBMavg6;	
by cluster;
run;
*average method with n=6 still not work. Cluster1 has over one thousand members whilr Cluster 7 has only 1 member;

*Complete method;
proc cluster data=IBMS simple noeigen method = complete rsquare nonorm out=tree;
title 'Cluster Analysis Complete';
var Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;
proc tree data=tree out=IBMcom nclusters=100;
copy Age EnvirSatisf HourlyR Jobinvol joblevel jobsatis monIncome YearsatCom Relasatisf Balance LastPromYear YearMGR;
run;

*Ward's method;
proc cluster data=IBMS simple noeigen method = ward rsquare nonorm out=tree;
title 'Cluster Analysis Ward';
var Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis;
run;
proc tree data=tree out=IBMward nclusters=100;
copy Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis;
run;
*Use 5 for the number of cluster according to the cutting point;
proc tree data=tree out=IBMward5 nclusters=5;
copy Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis;
run;
proc print data=IBMward5;
run;
proc means data=IBMward5;
var Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis;	
by cluster;
run;
proc sort data=IBMward5;
by cluster;
run;
*ward's method with n=5 seems to work, thus we profile it with boxplot;
proc boxplot data=IBMward5;	
plot (Age EnvirSatisf HourlyR Jobinvol joblevel monIncome Relasatisf Balance YearsatCom LastPromYear YearMGR jobsatis)*cluster;
run;
